### ISSUE TITLE
Add package for google-cloud-storage

### ISSUE THREAD

**Issue by dmaes** [theforeman/pulpcore-packaging#1244]
We are running pulp on GCP, and would like to use Google Storage Buckets as storage backend. Would it be possible to package google-cloud-storage? It seems to be required by `django-storages` to be able to use Google Storage.

Thanks in advance.

**Comment by ishan4421** [comment]
Hi @dmaes , You can surely do it. I used GCP for my NLP project but it wad not related to Django. I am attaching a chatgpt chat for it. I think it will work. I hope you have GCP json file. I hope this will work. 

 https://chatgpt.com/share/66e4859e-e25c-8006-818b-211c7af0fc8d

**Comment by Odilhao** [comment]
Hey @dmaes , looking at the [required](https://github.com/googleapis/python-storage/blob/main/setup.py#L30) packages atm we only have requests packaged, we would need to package 5 new packages. I'll try to take a look next week, we can draft the PRs, do you know if that's the only requirement for pulp to work with GCP Buckets?

**Comment by dmaes** [comment]
Hi @ishan4421, thanks for the "how", but that was not necessarily what I was asking, I figured that out already. My question was if it would be possible to make and add a `python-google-cloud-storage` RPM for the `google-cloud-storage` python package, since that is currently not present in this repository, but is required to actually be able to use Google cloud storage.

**Comment by dmaes** [comment]
HI @Odilhao, missed your comment while writing mine. As far as I understand the Django storages docs and the dependencies for [`django-storages[google]`](https://github.com/jschneier/django-storages/blob/b85d0214dada173059268d85fe5d318215480c08/pyproject.toml#L57) correctly, `google-cloud-storage`, allong with it's dependencies, should be the only requirement. But I will double-check on monday, and test it out with a pulp venv/pip install.

**Comment by dmaes** [comment]
Just tested, and can confirm that `google-cloud-storage`, along with it's dependencies, is enough.

**Comment by dmaes** [comment]
@Odilhao I tried creating a PR, not sure if it's any good, especially with the git annex stuff.

**Comment by dmaes** [comment]
@Odilhao thanks for the help. Everything running smoothly on GCS buckets now.
