### ISSUE TITLE
SCL based Pulp CLI not usable out of the box

### ISSUE THREAD

**Issue by quba42** [theforeman/pulpcore-packaging#370]
Please add a SCL wrapper skript like `tfm-ruby`.

Right now I get:
```
bash: pulp: command not found
```
After installing `yum install tfm-pulpcore-python3-pulp-cli`.

This is because the Pulp CLI binary is located at `/opt/theforeman/tfm-pulpcore/root/usr/bin/pulp`.

I can run `source scl_source enable tfm-pulpcore` and then I can use it, but this is not very user friendly.

**Comment by evgeni** [comment]
This has been fixed for 3.16 in https://github.com/theforeman/pulpcore-packaging/pull/426 and 3.17 in https://github.com/theforeman/pulpcore-packaging/pull/425
