### ISSUE TITLE
Missing pulp_manifest for 3.16 and 3.18

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/pulpcore-packaging#598]
Hi

I am currently looking for pulp_manifest on EL7 for pulpcore 3.18 which I cannot find.

* built package: [3.14/el7/source/python-pulp_manifest-3.0.0-1.el7.src.rpm](http://yum.theforeman.org/pulpcore/3.14/el7/source/python-pulp_manifest-3.0.0-1.el7.src.rpm)
* available SPEC files:
  * [3.14](https://github.com/theforeman/pulpcore-packaging/tree/rpm/3.14/packages/python-pulp-manifest)
  * [3.16](https://github.com/theforeman/pulpcore-packaging/tree/rpm/3.16/packages/python-pulp-manifest)
  * [3.18](https://github.com/theforeman/pulpcore-packaging/blob/rpm/3.18/packages/python-pulp-manifest/python-pulp-manifest.spec)

I was expecting that the SPEC file matches the build packages.

See also [foreman-documentation PR 1723: package name for "pulp_manifest" command](https://github.com/theforeman/foreman-documentation/pull/1723#discussion_r1010275148).

@Odilhao Can you please start the build pipeline?

See also https://github.com/theforeman/pulpcore-packaging/pull/562

**Comment by Lennonka** [comment]
FYI, we could probably use it for EL8 as well.

**Comment by ekohl** [comment]
FYI: there is https://github.com/theforeman/pulpcore-packaging/pull/596

**Comment by ekohl** [comment]
@Odilhao I think this is also needed in 3.21.

Speaking of which, should we change the default branch from 3.18 to 3.21?

**Comment by maximiliankolb** [comment]
Package is now available:

* http://yum.theforeman.org/pulpcore/3.16/el7/source/tfm-pulpcore-python-pulp_manifest-3.0.0-2.el7.src.rpm
* http://yum.theforeman.org/pulpcore/3.18/el7/source/tfm-pulpcore-python-pulp_manifest-3.0.0-3.el7.src.rpm

**Comment by ekohl** [comment]
Note those are the source RPMs. The actual RPMs are:
3.16:
* https://yum.theforeman.org/pulpcore/3.16/el7/x86_64/tfm-pulpcore-python3-pulp_manifest-3.0.0-2.el7.noarch.rpm
* https://yum.theforeman.org/pulpcore/3.16/el8/x86_64/python38-pulp_manifest-3.0.0-2.el8.noarch.rpm

3.18:
* https://yum.theforeman.org/pulpcore/3.18/el7/x86_64/tfm-pulpcore-python3-pulp_manifest-3.0.0-3.el7.noarch.rpm
* https://yum.theforeman.org/pulpcore/3.18/el8/x86_64/python39-pulp_manifest-3.0.0-3.el8.noarch.rpm

For 3.21 they haven't been published yet.
