### ISSUE TITLE
pulpcore-selinux for el9 is built against wrong selinux-policy version

### ISSUE THREAD

**Issue by wiad** [theforeman/pulpcore-packaging#729]
`pulpcore-selinux-1.3.3-1.el9.x86_64` has the following dependency:  
`selinux-policy >= 38.1.17-1.el9`  

Which is a version that is not available for RHEL9, so the package can't be installed.

**Comment by ekohl** [comment]
This has to do with our build roots. For 3.28 and older we used our own Koji which was using CentOS Stream. Starting 3.39 we build in COPR which has RHEL buildroots.
