### ISSUE TITLE
Add "pulp-manifest" package

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/pulpcore-packaging#810]
Hi :wave:

Please package [pulp-manifest](https://github.com/pulp/pulp-manifest/) again. It would be lovely if you backport it to [Pulpcore 3.39](https://github.com/theforeman/foreman-packaging/blob/rpm/3.9/packages/katello/rubygem-pulpcore_client/rubygem-pulpcore_client.spec) that goes with Foreman 3.9/Katello 4.11. :blue_heart: 

Just FYI:
* Last built package: [3.18](http://yum.theforeman.org/pulpcore/3.18/el8/x86_64/)
* Upstream docs: [Creating a Local Source for a File Type Repository](https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Creating_a_Local_Source_for_a_Custom_File_Type_Repository_content-management) + [Satellite docs](https://access.redhat.com/documentation/en-us/red_hat_satellite/6.14/html/managing_content/managing_custom_file_type_content_content-management#Creating_a_Remote_Source_for_a_Custom_File_Type_Repository_content-management)

**Comment by quba42** [comment]
https://github.com/theforeman/pulpcore-packaging/pull/814 :partying_face:

**Comment by maximiliankolb** [comment]
Closing this issue because nightly has pulp_manifest again.
